[en]
title = "My blog"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[pl]
title = "Blog"
description = "Trochę danych, trochę tenisa"
contentDir = "content/polski" 
weight = 2
LanguageDirection = "rtl" 
LanguageName = "PL"
