  [[main]]
  name = "strona główna"
  identifier = "main"
  weight = 100
  url = "/pl/"

  [[main]]
  name = "posty"
  weight = 200
  identifier = "posts"
  url = "/pl/post/"

  [[main]]
  name = "o mnie"
  weight = 300
  identifier = "about"
  url = "/pl/about/"

  [[main]]
  name = "kontakt"
  weight = 400
  identifier = "contact"
  url = "/pl/contact/"